from collections.abc import AsyncIterator
from typing import Any, Protocol


class IHttpResponse(Protocol):
    def raise_for_status(self) -> None: ...
    def json(self) -> Any: ...
    def aiter_lines(self) -> AsyncIterator[str]: ...
